apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "calendar-manager.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "calendar-manager.labels" . | nindent 4 }}
data:
  config.yaml: |
    port: {{ .Values.config.port }}
    logLevel: {{ .Values.config.logLevel | quote }}
    calendar:
      provider: {{ .Values.config.calendar.provider | quote }}
      google:
        credentialsFile: "/secrets/google-credentials.json"
        calendarID: {{ .Values.config.calendar.calendarID | quote }}
      icalURL: {{ .Values.config.calendar.icalURL | quote }}
