{{- if and .Values.googleCredentials (not .Values.existingCredentialsSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calendar-manager.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "calendar-manager.labels" . | nindent 4 }}
type: Opaque
data:
  google-credentials.json: {{ .Values.googleCredentials | quote }}
{{- end }}
